main: com.scivent.SCIvent
name: SCIvent
version: 1.0
api-version: "1.21.11"
author: "broccoli-head"

commands:
  lobby:
    description: "Teleports to the lobby."
    usage: /<command>
  duel:
    description: "Challenge a player for a duel!"
    usage: /<command>
  uhc:
    description: "Start the UHC game."
    usage: /<command>
  reset:
    description: "Emergency reset"
    usage: /<command>
