main: com.scivent.SCIvent
name: SCIvent
version: 1.0

commands:
  duel:
    description: "Challenge a player for a duel!"
    usage: /<command>
  uhc:
    description: "Start the UHC game."
    usage: /<command>
  reset:
    description: "Emergency reset"
    usage: /<command>
