main: com.scivent
name: SCIvent
version: 1.0

commands:
  duel:
    description: "Wyzwij innego gracza na pojedynek!"
    usage: /<command>
  reset:
    description: "Awaryjny reset"
    usage: /<command>
